[feature] 사용하는 권한 뷰 설정 및 권한 요청 흐름 변화
DeveloperAcademy-POSTECH/MC3-Team15-RockStars pull request #111
Opened 2023-08-16 13:50 UTC by Damagucci-Juice

# 📢 Description 
- 위치, 알림 권한을 즉시 요청하는 것이 아닌 알려주는 뷰를 띄우고 요청 

# 🔑 Key Changes
### 중심적으로 변화가 있는 부분을 명시해 주세요
- `DrivePalApp.swift`에서 요청하던 Request를 `AuthorizationRequestView`로 이관하였습니다. 
- 위치 권한을 가지고 있다면 `AuthorizationRequestView`가 나타나지 않습니다. 

# 📸 Screenshots
개발한 해당 부분의 스크린샷이나 영상을 첨부해 주세요
| 사용하는 정보 알림 | 위치 권한 | 알림 권한 | 
| -------- | ------- | ------- |
| ![정보 알림 뷰](https://github.com/DeveloperAcademy-POSTECH/MC3-Team15-RockStars/assets/50472122/21e0696d-8d27-4f86-affe-d8774db6ec96) |  ![위치 권한](https://github.com/DeveloperAcademy-POSTECH/MC3-Team15-RockStars/assets/50472122/ddae4c71-3f27-41ba-92d8-e47335e5921c) | ![알림권한](https://github.com/DeveloperAcademy-POSTECH/MC3-Team15-RockStars/assets/50472122/8b0c66db-5306-4f44-84b0-4169fff27bd6) |

# 🙏 To Reviewers
- figma에서 [TMAP 레퍼런스](https://www.figma.com/file/Vl1qDxx2ccBfnsujbxuqHc/MC3-%EB%9D%BD%EC%8A%A4%ED%83%80?type=design&node-id=1231%3A3230&mode=design&t=4Sw84BsMEt44OfIS-1)를 참고하였습니다. 
- `AuthorizationRequestView`에서 버튼 frame 잡을 때, frame으로 잡을지, padding으로 잡을지 여러분이라면 어떻게 하실지 궁금합니다.

close #101

2023-08-16 14:59 UTC, dayo2n approved these changes
수고 많으셨어요 구찌! 코드는 항상 깔끔하고 보기 좋네요 아이콘 위치가 애매하고 텍스트 간격에 조정이 살짝 필요할듯하네요 ㅎ 지금도 충분히 좋아요 !! 굿굿
버튼 프레임은.. 높이는 frame, 너비는 padding으로 주겠네요. 저는 대체로 가능한건 padding으로 다 조정하는 편이에요 최대한 모든 기기 디스플레이에서 일관적이게 보여주기 좋은 것 같아서! 
버튼 높이처럼 어느정도 고정되어 있는건 frame으로 잡는데.. 예전에 영에게 피드백 받으면서, 스유는 높이나 너비를 하드한 값을 주지 않고 패딩으로만 처리한다 고 말씀하신 적이 있는데 다음에 같이 여쭤보면 좋겠네여

2023-08-16 14:59 UTC, dayo2n commented on DrivePal/Sources/View/AuthorizationRequestView.swift
> +                    .frame(width: UIScreen.main.bounds.width-64)
이거 오 ㅐ이걸로 썼죠 ?! 구찌가 만든 `UIScreen.width`가 있었을텐데!!

2023-08-16 15:00 UTC, dayo2n commented
@jaelyung 저는 코드 위주로 리뷰했는데 동작 위주로 리뷰 부탁해요 레미 🥹🫶

2023-08-17 00:45 UTC, dayo2n requested changes
- [x] 알림 권한에 노티 추가
- [x] 권한없을시 설정앱으로 이동 화면 추가

2023-08-17 03:03 UTC, Damagucci-Juice commented
> * [ ]  권한없을시 설정앱으로 이동 화면 추가

이것도 기능 구현할까요?

2023-08-17 05:11 UTC, dayo2n commented
> > * [ ]   권한없을시 설정앱으로 이동 화면 추가
> 
> 이것도 기능 구현할까요?

했어욤 위치뜨고 알람뜨는데 화면 녹화하니까 보안때문인지 알림이 안보이네요 영상 첨부해요
| 허용안함 | 항상 허용 | 한번만 허용 | 
| -------- | ------- | ------- |
<img src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team15-RockStars/assets/57654681/8fe1873b-e73d-4777-8ee1-76abb69a613d" width="300">|<img src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team15-RockStars/assets/57654681/5867fc4f-7060-4cf4-8877-7a089b952e10" width="300">|<img src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team15-RockStars/assets/57654681/47f3bf6a-7207-419f-a03d-5964447ae1ba" width="300">|

2023-08-17 05:13 UTC, dayo2n approved these changes

2023-08-17 07:06 UTC, Damagucci-Juice reviewed
로직 깔끔하네요! 
이해하는데 큰 문제 없어요 ~

2023-08-17 07:11 UTC, dayo2n commented on DrivePal/Sources/View/AuthorizationRequestView.swift
> +import CoreLocation
넹!!

2023-08-17 07:50 UTC, merged