Refactor/segregating view and model
DeveloperAcademy-POSTECH/MC3-Team15-RockStars pull request #29
Opened 2023-07-18 03:44 UTC by Damagucci-Juice

# 제나, 제레미 파일 변경 다수 있습니다. 특히 `DrivePalView` 많이 변경됩니다! 

# 📢 Description
최소한의 리펙터링

# 🔑 Key Changes
### 중심적으로 변화가 있는 부분을 명시해 주세요
- `DrivePalView` 추가 
- extension 파일 추가
- DrivePalView 내부에서도 더 나눌 수 있는 부분이 있는지 알아보기! 

# 📸 Screenshots
기존 DrivePalView 라인: 151 줄
변경 DrivePalView 라인: 141 줄

# 🙏 To Reviewers
리뷰어가 확인하고 리뷰해 줬으면 좋겠는 부분을 알려주세요

2023-07-18 11:48 UTC, dayo2n requested changes
수고하셨어요 구찌!! 제가 수정하겠다고 한 부분 빼고 답글 & 수정 부탁드립니다 🤓
커밋메시지에 이슈 번호 ... 까비요!!!

2023-07-18 11:56 UTC, Damagucci-Juice commented on DrivePal/View/DrivingPalView.swift
> +    // TODO: - 뷰 생성 로직이 여기 담겨도 좋을까요?
`BackgroundScene`과 `SpriteView`에서 `motionStatus`에 따라서 애니메이션 변화를 담당하는 `ConvertibleBackgroundView`를 따로 만드는 것도 괜찮아보입니다?!

2023-07-18 11:57 UTC, dayo2n commented on DrivePal/View/DrivingPalView.swift
> +        }
지금보니까 이 놈 이상하네요 삼항연산자가 왜 안먹지!! 확인 필요 !!

2023-07-18 11:57 UTC, Damagucci-Juice commented on DrivePal/View/DrivingPalView.swift
> +        }
- 확인감사합니다!

2023-07-18 11:58 UTC, Damagucci-Juice commented on DrivePal/View/VelocityView.swift
> +    @State private var message: String = ""
- 그렇네요. 말씀해주신 부분이 더 이쁘다고 생각은 했는데, 습관에 따라서 한거 같아요. 수정해서 다시 푸시 할게요 !

2023-07-18 12:01 UTC, Damagucci-Juice commented on DrivePal/View/DrivingPalView.swift
> +        }
제가 수정해서 푸시할게요!

2023-07-18 17:38 UTC, dayo2n commented
충돌난거랑 자잘한건 처리했고 `ConvertibleBackgroundView` 요 뷰 분리하실거면 수정하신 뒤에 구찌가 머지해주세요 ~~ 저는 지금 머지 승인 남길게요!

2023-07-18 17:38 UTC, dayo2n approved these changes

2023-07-19 07:35 UTC, Damagucci-Juice commented
> 충돌난거랑 자잘한건 처리했고 `ConvertibleBackgroundView` 요 뷰 분리하실거면 수정하신 뒤에 구찌가 머지해주세요 ~~ 저는 지금 머지 승인 남길게요!

다음에 분리하도록 할게요. 애니메이션 생각보다 더 파봐야할거같아요! ㅎㅎ

2023-07-19 07:35 UTC, merged